services:
  postgres:
    image: postgres:16-alpine
    platform: linux/arm64
    environment:
      POSTGRES_DB: auvisa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/arm64
    ports:
      - "6333:6333"
    volumes:
      - qdrantdata:/qdrant/storage

volumes:
  pgdata:
  qdrantdata:
